# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3eaa44d2144055c5d4f29302498e9ff7068d4d70b091686d544971919684c2dcc6fec8362a668a04ed0734ecc212d539634e41a9c41f9c04d9a19c5186a4e50

test:
  secret_key_base: 8082a7d33fd36331692ecad53109269ef696737691c7d143884c704a6c748a60a1c537e21fa865e808f95f6b7658286b1cdbc3e3843a535073f265170fd19219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
